name: signify-backend
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - ultralytics>=8.3.0
      - torch==2.12.0
      - torchvision==0.27.0
      - fastapi
      - uvicorn[standard]
      - python-multipart
      - pydantic-settings
      - pillow
      - numpy
      - opencv-python
      - PyJWT==2.13.0
      - cryptography
      - locust
  - pytest
  - pytest-cov
  - httpx
