'use client';

/**
 * Landmark-based MLP classifier for BISINDO sign language.
 *
 * Runs entirely in the browser with zero npm dependencies — just loads a
 * weights.json file and performs forward-pass math in TypeScript.
 *
 * weights.json lives at public/models/landmark_mlp/weights.json and is
 * generated by packages/ml/scripts/train_mlp.py after collecting training
 * data with the /collect page.
 *
 * If the file doesn't exist yet, isReady stays false and predict() always
 * returns null — the app falls back to the CNN backend automatically.
 */

import { useCallback, useEffect, useRef, useState } from 'react';

const WEIGHTS_URL   = '/models/landmark_mlp/weights.json';
const LABEL_MAP_URL = '/models/landmark_mlp/label_map.json';

// ── Types ──────────────────────────────────────────────────────────────────

interface DenseLayer {
  W:      number[];   // flat row-major, shape (W_rows × W_cols)
  W_rows: number;
  W_cols: number;
  b:      number[];
}

interface ModelWeights {
  layers: DenseLayer[];
}

export interface LandmarkPoint { x: number; y: number; z: number; }

export interface LMClassifierResult {
  prediction:    string;
  confidence:    number;
  low_confidence: boolean;
}

// ── Inference math (no deps, ~0.1 ms for this model size) ─────────────────

/** Normalize 21 MediaPipe landmarks → 63-float position/scale-invariant vector. */
export function normalizeLandmarks(lms: LandmarkPoint[]): number[] {
  const wx = lms[0].x, wy = lms[0].y, wz = lms[0].z;
  const coords = lms.map(lm => [lm.x - wx, lm.y - wy, lm.z - wz]);

  // Scale by wrist → middle-finger MCP (index 9) distance
  const ref   = coords[9];
  const scale = Math.sqrt(ref[0] ** 2 + ref[1] ** 2 + ref[2] ** 2);
  if (scale > 1e-6) {
    for (const c of coords) { c[0] /= scale; c[1] /= scale; c[2] /= scale; }
  }
  return coords.flat();
}

function matmul(x: number[], layer: DenseLayer): number[] {
  const { W, W_rows, W_cols, b } = layer;
  const out = new Array<number>(W_cols);
  for (let j = 0; j < W_cols; j++) {
    let s = b[j];
    for (let i = 0; i < W_rows; i++) s += x[i] * W[i * W_cols + j];
    out[j] = s;
  }
  return out;
}

function relu(x: number[]): number[] {
  return x.map(v => (v > 0 ? v : 0));
}

function softmax(x: number[]): number[] {
  const max = Math.max(...x);
  const exp = x.map(v => Math.exp(v - max));
  const sum = exp.reduce((a, b) => a + b, 0);
  return exp.map(v => v / sum);
}

function forward(input: number[], weights: ModelWeights): number[] {
  let x = input;
  for (let i = 0; i < weights.layers.length; i++) {
    x = matmul(x, weights.layers[i]);
    if (i < weights.layers.length - 1) x = relu(x);
  }
  return softmax(x);
}

// ── Hook ───────────────────────────────────────────────────────────────────

export function useLandmarkClassifier(threshold = 0.6) {
  const weightsRef  = useRef<ModelWeights | null>(null);
  const labelMapRef = useRef<Record<string, string>>({});
  const [isReady, setIsReady] = useState(false);

  useEffect(() => {
    let cancelled = false;
    Promise.all([
      fetch(WEIGHTS_URL).then(r => r.ok ? r.json() : Promise.reject()),
      fetch(LABEL_MAP_URL).then(r => r.ok ? r.json() : Promise.reject()),
    ])
      .then(([weights, labelMap]) => {
        if (cancelled) return;
        weightsRef.current  = weights as ModelWeights;
        labelMapRef.current = labelMap as Record<string, string>;
        setIsReady(true);
        console.info('[LandmarkClassifier] loaded', weights.layers.length, 'layers');
      })
      .catch(() => {
        // weights.json not found yet — silent fallback to CNN
      });
    return () => { cancelled = true; };
  }, []);

  const predict = useCallback(
    (landmarks: LandmarkPoint[]): LMClassifierResult | null => {
      if (!weightsRef.current) return null;
      const input  = normalizeLandmarks(landmarks);
      const probs  = forward(input, weightsRef.current);
      const bestIdx = probs.indexOf(Math.max(...probs));
      const conf    = probs[bestIdx];
      return {
        prediction:     labelMapRef.current[String(bestIdx)] ?? '?',
        confidence:     conf,
        low_confidence: conf < threshold,
      };
    },
    [threshold],
  );

  return { isReady, predict };
}
