name: signify-ml
channels:
  - conda-forge
  - nvidia          # ← Tambahkan channel ini untuk akses CUDA 12.3 yang asli
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - opencv
  - scikit-learn
  - pillow
  - tqdm
  - pyyaml
  # Gunakan cuda-version untuk mengunci versi toolkit di conda
  - cuda-version=12.3
  - cudnn=8.9.7     # ← Versi 8.9.x sangat stabil untuk TF 2.16
  - pip
  - pip:
    - tensorflow==2.16.2  # [and-cuda] tidak wajib jika sudah diatur di conda
    - protobuf==4.25.3
    - absl-py
    - pycocotools
    - wandb